---
# Update apt-cache and install the latest packages
- hosts: all
  become: yes
  roles:
    - common

# Install kafka, zookeeper, redis, virtualenv
- include: zookeeper.yml
- include: kafka.yml
- include: redis.yml
- include: virtualenv.yml
